services:

  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Spartans@123
    ports:
      - "5432:5432"
    networks:
      - chatbot_network

  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - chatbot_network
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chatbot_network

networks:
  chatbot_network:
    driver: bridge

volumes:
  postgres_data:
